param containerapps_c964_capp_name string = 'c964-capp'
param virtualNetworks_c964_vnet_name string = 'c964-vnet'
param storageAccounts_c964store_name string = 'c964store'
param privateEndpoints_c964storepep_name string = 'c964storepep'
param namespaces_c964_relay_namespace_name string = 'c964-relay-namespace'
param privateEndpoints_ai_search_pep_name string = 'ai-search-pep'
param registries_c964registry_name string = 'c964registry'
param networkSecurityGroups_c964_vm_nsg_name string = 'c964-vm-nsg'
param searchServices_c964_ai_search_basic_name string = 'c964-ai-search-basic'
param networkSecurityGroups_aifoundry_nsg_name string = 'aifoundry-nsg'
param storageAccounts_c964cloudshellstore_name string = 'c964cloudshellstore'
param accounts_c964_openai_resource_name string = 'c964-openai-resource'
param privateEndpoints_cloudshellRelayEndpoint_name string = 'cloudshellRelayEndpoint'
param managedEnvironments_c964_capp_managedEnvironment_name string = 'c964-capp-managedEnvironment'
param privateDnsZones_privatelink_openai_azure_com_name string = 'privatelink.openai.azure.com'
param privateDnsZones_privatelink_search_windows_net_name string = 'privatelink.search.windows.net'
param privateDnsZones_privatelink_aiservices_azure_com_name string = 'privatelink.aiservices.azure.com'
param networkProfiles_aci_networkProfile_southcentralus_name string = 'aci-networkProfile-southcentralus'
param privateDnsZones_privatelink_blob_core_windows_net_name string = 'privatelink.blob.core.windows.net'
param privateDnsZones_privatelink_servicebus_windows_net_name string = 'privatelink.servicebus.windows.net'
param networkSecurityGroups_c964_vnet_openai_nsg_southcentralus_name string = 'c964-vnet-openai-nsg-southcentralus'
param networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name string = 'c964-vnet-default-nsg-southcentralus'
param networkSecurityGroups_c964_vnet_containerapps_nsg_southcentralus_name string = 'c964-vnet-containerapps-nsg-southcentralus'
param networkSecurityGroups_c964_vnet_privateendpoint_nsg_southcentralus_name string = 'c964-vnet-privateendpoint-nsg-southcentralus'
param userAssignedIdentities_c964_capp_managedEnvironmentc964registryc964_capstone_rgOidc_name string = 'c964-capp-managedEnvironmentc964registryc964-capstone-rgOidc'

resource accounts_c964_openai_resource_name_resource 'Microsoft.CognitiveServices/accounts@2025-06-01' = {
  name: accounts_c964_openai_resource_name
  location: 'swedencentral'
  sku: {
    name: 'S0'
  }
  kind: 'AIServices'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    apiProperties: {}
    customSubDomainName: accounts_c964_openai_resource_name
    networkAcls: {
      defaultAction: 'Allow'
      virtualNetworkRules: []
      ipRules: []
    }
    allowProjectManagement: true
    defaultProject: 'c964-openai'
    associatedProjects: [
      'c964-openai'
    ]
    publicNetworkAccess: 'Enabled'
    disableLocalAuth: false
  }
}

resource registries_c964registry_name_resource 'Microsoft.ContainerRegistry/registries@2025-05-01-preview' = {
  name: registries_c964registry_name
  location: 'southcentralus'
  sku: {
    name: 'Basic'
    tier: 'Basic'
  }
  properties: {
    adminUserEnabled: true
    policies: {
      quarantinePolicy: {
        status: 'disabled'
      }
      trustPolicy: {
        type: 'Notary'
        status: 'disabled'
      }
      retentionPolicy: {
        days: 7
        status: 'disabled'
      }
      exportPolicy: {
        status: 'enabled'
      }
      azureADAuthenticationAsArmPolicy: {
        status: 'enabled'
      }
      softDeletePolicy: {
        retentionDays: 7
        status: 'disabled'
      }
    }
    encryption: {
      status: 'disabled'
    }
    dataEndpointEnabled: false
    publicNetworkAccess: 'Enabled'
    networkRuleBypassOptions: 'AzureServices'
    networkRuleBypassAllowedForTasks: false
    zoneRedundancy: 'Disabled'
    anonymousPullEnabled: false
    metadataSearch: 'Disabled'
    roleAssignmentMode: 'LegacyRegistryPermissions'
    autoGeneratedDomainNameLabelScope: 'Unsecure'
  }
}

resource userAssignedIdentities_c964_capp_managedEnvironmentc964registryc964_capstone_rgOidc_name_resource 'Microsoft.ManagedIdentity/userAssignedIdentities@2025-01-31-preview' = {
  name: userAssignedIdentities_c964_capp_managedEnvironmentc964registryc964_capstone_rgOidc_name
  location: 'southcentralus'
}

resource networkSecurityGroups_aifoundry_nsg_name_resource 'Microsoft.Network/networkSecurityGroups@2024-07-01' = {
  name: networkSecurityGroups_aifoundry_nsg_name
  location: 'southcentralus'
  properties: {
    securityRules: []
  }
}

resource networkSecurityGroups_c964_vm_nsg_name_resource 'Microsoft.Network/networkSecurityGroups@2024-07-01' = {
  name: networkSecurityGroups_c964_vm_nsg_name
  location: 'southcentralus'
  properties: {
    securityRules: [
      {
        name: 'AllowBastionHostCommunication'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowBastionHostCommunication.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          sourceAddressPrefix: 'VirtualNetwork'
          destinationAddressPrefix: 'VirtualNetwork'
          access: 'Allow'
          priority: 1003
          direction: 'Inbound'
          sourcePortRanges: []
          destinationPortRanges: [
            '8080'
            '5701'
          ]
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
      {
        name: 'AllowAzureLoadBalancerInbound'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowAzureLoadBalancerInbound.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: 'TCP'
          sourcePortRange: '*'
          destinationPortRange: '443'
          sourceAddressPrefix: 'AzureLoadBalancer'
          destinationAddressPrefix: '*'
          access: 'Allow'
          priority: 1002
          direction: 'Inbound'
          sourcePortRanges: []
          destinationPortRanges: []
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
      {
        name: 'AllowGatewayManagerInbound'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowGatewayManagerInbound.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: 'TCP'
          sourcePortRange: '*'
          destinationPortRange: '443'
          sourceAddressPrefix: 'GatewayManager'
          destinationAddressPrefix: '*'
          access: 'Allow'
          priority: 1001
          direction: 'Inbound'
          sourcePortRanges: []
          destinationPortRanges: []
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
      {
        name: 'AllowHttpsInbound'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowHttpsInbound.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: 'TCP'
          sourcePortRange: '*'
          destinationPortRange: '443'
          sourceAddressPrefix: 'Internet'
          destinationAddressPrefix: '*'
          access: 'Allow'
          priority: 1000
          direction: 'Inbound'
          sourcePortRanges: []
          destinationPortRanges: []
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
      {
        name: 'AllowSshRdpOutbound'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowSshRdpOutbound.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          sourceAddressPrefix: '*'
          destinationAddressPrefix: 'VirtualNetwork'
          access: 'Allow'
          priority: 100
          direction: 'Outbound'
          sourcePortRanges: []
          destinationPortRanges: [
            '22'
            '3389'
          ]
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
      {
        name: 'AllowAzureCloudOutbound'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowAzureCloudOutbound.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: 'TCP'
          sourcePortRange: '*'
          destinationPortRange: '443'
          sourceAddressPrefix: '*'
          destinationAddressPrefix: 'AzureCloud'
          access: 'Allow'
          priority: 110
          direction: 'Outbound'
          sourcePortRanges: []
          destinationPortRanges: []
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
      {
        name: 'AllowBastionCommunicationOutbound'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowBastionCommunicationOutbound.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          sourceAddressPrefix: 'VirtualNetwork'
          destinationAddressPrefix: 'VirtualNetwork'
          access: 'Allow'
          priority: 120
          direction: 'Outbound'
          sourcePortRanges: []
          destinationPortRanges: [
            '8080'
            '5701'
          ]
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
      {
        name: 'AllowHttpOutbound'
        id: networkSecurityGroups_c964_vm_nsg_name_AllowHttpOutbound.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          protocol: 'TCP'
          sourcePortRange: '*'
          destinationPortRange: '80'
          sourceAddressPrefix: '*'
          destinationAddressPrefix: 'Internet'
          access: 'Allow'
          priority: 130
          direction: 'Outbound'
          sourcePortRanges: []
          destinationPortRanges: []
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
    ]
  }
}

resource networkSecurityGroups_c964_vnet_containerapps_nsg_southcentralus_name_resource 'Microsoft.Network/networkSecurityGroups@2024-07-01' = {
  name: networkSecurityGroups_c964_vnet_containerapps_nsg_southcentralus_name
  location: 'southcentralus'
  properties: {
    securityRules: []
  }
}

resource networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource 'Microsoft.Network/networkSecurityGroups@2024-07-01' = {
  name: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name
  location: 'southcentralus'
  properties: {
    securityRules: [
      {
        name: 'DenyIntraSubnetTraffic'
        id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_DenyIntraSubnetTraffic.id
        type: 'Microsoft.Network/networkSecurityGroups/securityRules'
        properties: {
          description: 'Deny traffic between container groups in cloudshellsubnet'
          protocol: '*'
          sourcePortRange: '*'
          destinationPortRange: '*'
          sourceAddressPrefix: '10.0.10.0/26'
          destinationAddressPrefix: '10.0.10.0/26'
          access: 'Deny'
          priority: 100
          direction: 'Inbound'
          sourcePortRanges: []
          destinationPortRanges: []
          sourceAddressPrefixes: []
          destinationAddressPrefixes: []
        }
      }
    ]
  }
}

resource networkSecurityGroups_c964_vnet_openai_nsg_southcentralus_name_resource 'Microsoft.Network/networkSecurityGroups@2024-07-01' = {
  name: networkSecurityGroups_c964_vnet_openai_nsg_southcentralus_name
  location: 'southcentralus'
  properties: {
    securityRules: []
  }
}

resource networkSecurityGroups_c964_vnet_privateendpoint_nsg_southcentralus_name_resource 'Microsoft.Network/networkSecurityGroups@2024-07-01' = {
  name: networkSecurityGroups_c964_vnet_privateendpoint_nsg_southcentralus_name
  location: 'southcentralus'
  properties: {
    securityRules: []
  }
}

resource privateDnsZones_privatelink_aiservices_azure_com_name_resource 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: privateDnsZones_privatelink_aiservices_azure_com_name
  location: 'global'
  properties: {}
}

resource privateDnsZones_privatelink_blob_core_windows_net_name_resource 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: privateDnsZones_privatelink_blob_core_windows_net_name
  location: 'global'
  properties: {}
}

resource privateDnsZones_privatelink_openai_azure_com_name_resource 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: privateDnsZones_privatelink_openai_azure_com_name
  location: 'global'
  properties: {}
}

resource privateDnsZones_privatelink_search_windows_net_name_resource 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: privateDnsZones_privatelink_search_windows_net_name
  location: 'global'
  properties: {}
}

resource privateDnsZones_privatelink_servicebus_windows_net_name_resource 'Microsoft.Network/privateDnsZones@2024-06-01' = {
  name: privateDnsZones_privatelink_servicebus_windows_net_name
  location: 'global'
  tags: {
    Environment: 'cloudshell'
  }
  properties: {}
}

resource searchServices_c964_ai_search_basic_name_resource 'Microsoft.Search/searchServices@2025-05-01' = {
  name: searchServices_c964_ai_search_basic_name
  location: 'South Central US'
  sku: {
    name: 'basic'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    replicaCount: 1
    partitionCount: 1
    endpoint: 'https://${searchServices_c964_ai_search_basic_name}.search.windows.net'
    hostingMode: 'default'
    computeType: 'Default'
    publicNetworkAccess: 'Enabled'
    networkRuleSet: {
      ipRules: []
      bypass: 'AzureServices'
    }
    encryptionWithCmk: {
      enforcement: 'Unspecified'
    }
    disableLocalAuth: false
    authOptions: {
      aadOrApiKey: {
        aadAuthFailureMode: 'http401WithBearerChallenge'
      }
    }
    dataExfiltrationProtections: []
    semanticSearch: 'free'
    upgradeAvailable: 'notAvailable'
  }
}

resource containerapps_c964_capp_name_resource 'Microsoft.App/containerapps@2025-02-02-preview' = {
  name: containerapps_c964_capp_name
  location: 'South Central US'
  kind: 'containerapps'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    managedEnvironmentId: managedEnvironments_c964_capp_managedEnvironment_name_resource.id
    environmentId: managedEnvironments_c964_capp_managedEnvironment_name_resource.id
    workloadProfileName: 'Consumption'
    configuration: {
      activeRevisionsMode: 'Single'
      ingress: {
        external: true
        targetPort: 8000
        exposedPort: 0
        transport: 'Auto'
        traffic: [
          {
            weight: 100
            latestRevision: true
          }
        ]
        allowInsecure: false
        clientCertificateMode: 'Ignore'
        stickySessions: {
          affinity: 'none'
        }
      }
      registries: [
        {
          server: 'c964registry.azurecr.io'
          identity: 'system-environment'
        }
      ]
      identitySettings: []
      maxInactiveRevisions: 100
    }
    template: {
      containers: [
        {
          image: 'c964registry.azurecr.io/arm-template-generator:latest'
          imageType: 'ContainerImage'
          name: containerapps_c964_capp_name
          env: [
            {
              name: 'AZURE_SEARCH_SERVICE_ENDPOINT'
              value: 'https://c964-ai-search-basic.search.windows.net'
            }
            {
              name: 'AZURE_OPENAI_ENDPOINT'
              value: 'https://c964-openai-resource.services.ai.azure.com/'
            }
            {
              name: 'AZURE_OPENAI_DEPLOYMENT_NAME'
              value: 'gpt-4o-mini-2024-07-18-ft-f5669b4111424563a3951e228c98ea96'
            }
            {
              name: 'AZURE_SEARCH_INDEX_NAME'
              value: 'avm-modules-index'
            }
          ]
          resources: {
            cpu: json('0.25')
            memory: '0.5Gi'
          }
          probes: []
        }
      ]
      scale: {
        minReplicas: 0
        maxReplicas: 5
        cooldownPeriod: 300
        pollingInterval: 30
      }
      volumes: []
    }
  }
}

resource managedEnvironments_c964_capp_managedEnvironment_name_resource 'Microsoft.App/managedEnvironments@2025-02-02-preview' = {
  name: managedEnvironments_c964_capp_managedEnvironment_name
  location: 'South Central US'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    vnetConfiguration: {
      internal: false
      infrastructureSubnetId: virtualNetworks_c964_vnet_name_containerapps.id
    }
    appLogsConfiguration: {}
    zoneRedundant: false
    kedaConfiguration: {}
    daprConfiguration: {}
    customDomainConfiguration: {}
    workloadProfiles: [
      {
        workloadProfileType: 'Consumption'
        name: 'Consumption'
        enableFips: false
      }
    ]
    infrastructureResourceGroup: 'ME_${managedEnvironments_c964_capp_managedEnvironment_name}_c964-capstone-rg_southcentralus'
    peerAuthentication: {
      mtls: {
        enabled: false
      }
    }
    peerTrafficConfiguration: {
      encryption: {
        enabled: false
      }
    }
    publicNetworkAccess: 'Enabled'
  }
}

resource managedEnvironments_c964_capp_managedEnvironment_name_aspire_dashboard 'Microsoft.App/managedEnvironments/dotNetComponents@2025-02-02-preview' = {
  parent: managedEnvironments_c964_capp_managedEnvironment_name_resource
  name: 'aspire-dashboard'
  properties: {
    componentType: 'AspireDashboard'
  }
}

resource accounts_c964_openai_resource_name_Default 'Microsoft.CognitiveServices/accounts/defenderForAISettings@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_resource
  name: 'Default'
  properties: {
    state: 'Disabled'
  }
}

resource accounts_c964_openai_resource_name_gpt_4o_mini_2024_07_18_ft_f5669b4111424563a3951e228c98ea96 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_resource
  name: 'gpt-4o-mini-2024-07-18-ft-f5669b4111424563a3951e228c98ea96'
  sku: {
    name: 'GlobalStandard'
    capacity: 50
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: 'gpt-4o-mini-2024-07-18.ft-f5669b4111424563a3951e228c98ea96'
      version: '1'
    }
    versionUpgradeOption: 'NoAutoUpgrade'
    currentCapacity: 50
  }
}

resource accounts_c964_openai_resource_name_text_embedding_3_large 'Microsoft.CognitiveServices/accounts/deployments@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_resource
  name: 'text-embedding-3-large'
  sku: {
    name: 'GlobalStandard'
    capacity: 150
  }
  properties: {
    model: {
      format: 'OpenAI'
      name: 'text-embedding-3-large'
      version: '1'
    }
    versionUpgradeOption: 'NoAutoUpgrade'
    currentCapacity: 150
    raiPolicyName: 'Microsoft.DefaultV2'
  }
}

resource accounts_c964_openai_resource_name_c964_openai 'Microsoft.CognitiveServices/accounts/projects@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_resource
  name: 'c964-openai'
  location: 'swedencentral'
  kind: 'AIServices'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {}
}

resource accounts_c964_openai_resource_name_Microsoft_Default 'Microsoft.CognitiveServices/accounts/raiPolicies@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_resource
  name: 'Microsoft.Default'
  properties: {
    mode: 'Blocking'
    contentFilters: [
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
    ]
  }
}

resource accounts_c964_openai_resource_name_Microsoft_DefaultV2 'Microsoft.CognitiveServices/accounts/raiPolicies@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_resource
  name: 'Microsoft.DefaultV2'
  properties: {
    mode: 'Blocking'
    contentFilters: [
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Hate'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Sexual'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Violence'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Selfharm'
        severityThreshold: 'Medium'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Jailbreak'
        blocking: true
        enabled: true
        source: 'Prompt'
      }
      {
        name: 'Protected Material Text'
        blocking: true
        enabled: true
        source: 'Completion'
      }
      {
        name: 'Protected Material Code'
        blocking: false
        enabled: true
        source: 'Completion'
      }
    ]
  }
}

resource registries_c964registry_name_repositories_admin 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_c964registry_name_resource
  name: '_repositories_admin'
  properties: {
    description: 'Can perform all read, write and delete operations on the registry'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
      'repositories/*/content/delete'
    ]
  }
}

resource registries_c964registry_name_repositories_pull 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_c964registry_name_resource
  name: '_repositories_pull'
  properties: {
    description: 'Can pull any repository of the registry'
    actions: [
      'repositories/*/content/read'
    ]
  }
}

resource registries_c964registry_name_repositories_pull_metadata_read 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_c964registry_name_resource
  name: '_repositories_pull_metadata_read'
  properties: {
    description: 'Can perform all read operations on the registry'
    actions: [
      'repositories/*/content/read'
      'repositories/*/metadata/read'
    ]
  }
}

resource registries_c964registry_name_repositories_push 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_c964registry_name_resource
  name: '_repositories_push'
  properties: {
    description: 'Can push to any repository of the registry'
    actions: [
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

resource registries_c964registry_name_repositories_push_metadata_write 'Microsoft.ContainerRegistry/registries/scopeMaps@2025-05-01-preview' = {
  parent: registries_c964registry_name_resource
  name: '_repositories_push_metadata_write'
  properties: {
    description: 'Can perform all read and write operations on the registry'
    actions: [
      'repositories/*/metadata/read'
      'repositories/*/metadata/write'
      'repositories/*/content/read'
      'repositories/*/content/write'
    ]
  }
}

resource userAssignedIdentities_c964_capp_managedEnvironmentc964registryc964_capstone_rgOidc_name_c964_capp_fed 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2025-01-31-preview' = {
  parent: userAssignedIdentities_c964_capp_managedEnvironmentc964registryc964_capstone_rgOidc_name_resource
  name: 'c964-capp-fed'
  properties: {
    issuer: 'https://token.actions.githubusercontent.com'
    subject: 'repo:jostubbl_microsoft/arm-template-generator:ref:refs/heads/main'
    audiences: [
      'api://AzureADTokenExchange'
    ]
  }
}

resource networkProfiles_aci_networkProfile_southcentralus_name_resource 'Microsoft.Network/networkProfiles@2024-07-01' = {
  name: networkProfiles_aci_networkProfile_southcentralus_name
  location: 'southcentralus'
  tags: {
    Environment: 'cloudshell'
  }
  properties: {
    containerNetworkInterfaceConfigurations: [
      {
        name: 'eth-cloudshellsubnet'
        id: '${networkProfiles_aci_networkProfile_southcentralus_name_resource.id}/containerNetworkInterfaceConfigurations/eth-cloudshellsubnet'
        properties: {
          ipConfigurations: [
            {
              name: 'ipconfig-cloudshellsubnet'
              id: '${networkProfiles_aci_networkProfile_southcentralus_name_resource.id}/containerNetworkInterfaceConfigurations/eth-cloudshellsubnet/ipConfigurations/ipconfig-cloudshellsubnet'
              properties: {
                subnet: {
                  id: virtualNetworks_c964_vnet_name_cloudshellsubnet.id
                }
              }
            }
          ]
        }
      }
    ]
  }
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowAzureCloudOutbound 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowAzureCloudOutbound'
  properties: {
    protocol: 'TCP'
    sourcePortRange: '*'
    destinationPortRange: '443'
    sourceAddressPrefix: '*'
    destinationAddressPrefix: 'AzureCloud'
    access: 'Allow'
    priority: 110
    direction: 'Outbound'
    sourcePortRanges: []
    destinationPortRanges: []
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowAzureLoadBalancerInbound 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowAzureLoadBalancerInbound'
  properties: {
    protocol: 'TCP'
    sourcePortRange: '*'
    destinationPortRange: '443'
    sourceAddressPrefix: 'AzureLoadBalancer'
    destinationAddressPrefix: '*'
    access: 'Allow'
    priority: 1002
    direction: 'Inbound'
    sourcePortRanges: []
    destinationPortRanges: []
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowBastionCommunicationOutbound 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowBastionCommunicationOutbound'
  properties: {
    protocol: '*'
    sourcePortRange: '*'
    sourceAddressPrefix: 'VirtualNetwork'
    destinationAddressPrefix: 'VirtualNetwork'
    access: 'Allow'
    priority: 120
    direction: 'Outbound'
    sourcePortRanges: []
    destinationPortRanges: [
      '8080'
      '5701'
    ]
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowBastionHostCommunication 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowBastionHostCommunication'
  properties: {
    protocol: '*'
    sourcePortRange: '*'
    sourceAddressPrefix: 'VirtualNetwork'
    destinationAddressPrefix: 'VirtualNetwork'
    access: 'Allow'
    priority: 1003
    direction: 'Inbound'
    sourcePortRanges: []
    destinationPortRanges: [
      '8080'
      '5701'
    ]
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowGatewayManagerInbound 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowGatewayManagerInbound'
  properties: {
    protocol: 'TCP'
    sourcePortRange: '*'
    destinationPortRange: '443'
    sourceAddressPrefix: 'GatewayManager'
    destinationAddressPrefix: '*'
    access: 'Allow'
    priority: 1001
    direction: 'Inbound'
    sourcePortRanges: []
    destinationPortRanges: []
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowHttpOutbound 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowHttpOutbound'
  properties: {
    protocol: 'TCP'
    sourcePortRange: '*'
    destinationPortRange: '80'
    sourceAddressPrefix: '*'
    destinationAddressPrefix: 'Internet'
    access: 'Allow'
    priority: 130
    direction: 'Outbound'
    sourcePortRanges: []
    destinationPortRanges: []
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowHttpsInbound 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowHttpsInbound'
  properties: {
    protocol: 'TCP'
    sourcePortRange: '*'
    destinationPortRange: '443'
    sourceAddressPrefix: 'Internet'
    destinationAddressPrefix: '*'
    access: 'Allow'
    priority: 1000
    direction: 'Inbound'
    sourcePortRanges: []
    destinationPortRanges: []
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vm_nsg_name_AllowSshRdpOutbound 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vm_nsg_name}/AllowSshRdpOutbound'
  properties: {
    protocol: '*'
    sourcePortRange: '*'
    sourceAddressPrefix: '*'
    destinationAddressPrefix: 'VirtualNetwork'
    access: 'Allow'
    priority: 100
    direction: 'Outbound'
    sourcePortRanges: []
    destinationPortRanges: [
      '22'
      '3389'
    ]
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vm_nsg_name_resource
  ]
}

resource networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_DenyIntraSubnetTraffic 'Microsoft.Network/networkSecurityGroups/securityRules@2024-07-01' = {
  name: '${networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name}/DenyIntraSubnetTraffic'
  properties: {
    description: 'Deny traffic between container groups in cloudshellsubnet'
    protocol: '*'
    sourcePortRange: '*'
    destinationPortRange: '*'
    sourceAddressPrefix: '10.0.10.0/26'
    destinationAddressPrefix: '10.0.10.0/26'
    access: 'Deny'
    priority: 100
    direction: 'Inbound'
    sourcePortRanges: []
    destinationPortRanges: []
    sourceAddressPrefixes: []
    destinationAddressPrefixes: []
  }
  dependsOn: [
    networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource
  ]
}

resource privateDnsZones_privatelink_aiservices_azure_com_name_c964_aifoundry 'Microsoft.Network/privateDnsZones/A@2024-06-01' = {
  parent: privateDnsZones_privatelink_aiservices_azure_com_name_resource
  name: 'c964-aifoundry'
  properties: {
    ttl: 3600
    aRecords: [
      {
        ipv4Address: '10.0.1.6'
      }
    ]
  }
}

resource privateDnsZones_privatelink_search_windows_net_name_c964_ai_search_basic 'Microsoft.Network/privateDnsZones/A@2024-06-01' = {
  parent: privateDnsZones_privatelink_search_windows_net_name_resource
  name: 'c964-ai-search-basic'
  properties: {
    metadata: {
      creator: 'created by private endpoint ai-search-pep with resource guid 6d4adb19-3c17-43d8-b23a-5bc542a705f7'
    }
    ttl: 10
    aRecords: [
      {
        ipv4Address: '10.0.6.4'
      }
    ]
  }
}

resource privateDnsZones_privatelink_servicebus_windows_net_name_c964_relay_namespace 'Microsoft.Network/privateDnsZones/A@2024-06-01' = {
  parent: privateDnsZones_privatelink_servicebus_windows_net_name_resource
  name: 'c964-relay-namespace'
  properties: {
    ttl: 3600
    aRecords: [
      {
        ipv4Address: '10.0.11.4'
      }
    ]
  }
}

resource privateDnsZones_privatelink_blob_core_windows_net_name_c964store 'Microsoft.Network/privateDnsZones/A@2024-06-01' = {
  parent: privateDnsZones_privatelink_blob_core_windows_net_name_resource
  name: 'c964store'
  properties: {
    metadata: {
      creator: 'created by private endpoint c964storepep with resource guid 72db2654-02a0-43a7-b200-f786a1c66e90'
    }
    ttl: 10
    aRecords: [
      {
        ipv4Address: '10.0.6.5'
      }
    ]
  }
}

resource Microsoft_Network_privateDnsZones_SOA_privateDnsZones_privatelink_aiservices_azure_com_name 'Microsoft.Network/privateDnsZones/SOA@2024-06-01' = {
  parent: privateDnsZones_privatelink_aiservices_azure_com_name_resource
  name: '@'
  properties: {
    ttl: 3600
    soaRecord: {
      email: 'azureprivatedns-host.microsoft.com'
      expireTime: 2419200
      host: 'azureprivatedns.net'
      minimumTtl: 10
      refreshTime: 3600
      retryTime: 300
      serialNumber: 1
    }
  }
}

resource Microsoft_Network_privateDnsZones_SOA_privateDnsZones_privatelink_blob_core_windows_net_name 'Microsoft.Network/privateDnsZones/SOA@2024-06-01' = {
  parent: privateDnsZones_privatelink_blob_core_windows_net_name_resource
  name: '@'
  properties: {
    ttl: 3600
    soaRecord: {
      email: 'azureprivatedns-host.microsoft.com'
      expireTime: 2419200
      host: 'azureprivatedns.net'
      minimumTtl: 10
      refreshTime: 3600
      retryTime: 300
      serialNumber: 1
    }
  }
}

resource Microsoft_Network_privateDnsZones_SOA_privateDnsZones_privatelink_openai_azure_com_name 'Microsoft.Network/privateDnsZones/SOA@2024-06-01' = {
  parent: privateDnsZones_privatelink_openai_azure_com_name_resource
  name: '@'
  properties: {
    ttl: 3600
    soaRecord: {
      email: 'azureprivatedns-host.microsoft.com'
      expireTime: 2419200
      host: 'azureprivatedns.net'
      minimumTtl: 10
      refreshTime: 3600
      retryTime: 300
      serialNumber: 1
    }
  }
}

resource Microsoft_Network_privateDnsZones_SOA_privateDnsZones_privatelink_search_windows_net_name 'Microsoft.Network/privateDnsZones/SOA@2024-06-01' = {
  parent: privateDnsZones_privatelink_search_windows_net_name_resource
  name: '@'
  properties: {
    ttl: 3600
    soaRecord: {
      email: 'azureprivatedns-host.microsoft.com'
      expireTime: 2419200
      host: 'azureprivatedns.net'
      minimumTtl: 10
      refreshTime: 3600
      retryTime: 300
      serialNumber: 1
    }
  }
}

resource Microsoft_Network_privateDnsZones_SOA_privateDnsZones_privatelink_servicebus_windows_net_name 'Microsoft.Network/privateDnsZones/SOA@2024-06-01' = {
  parent: privateDnsZones_privatelink_servicebus_windows_net_name_resource
  name: '@'
  properties: {
    ttl: 3600
    soaRecord: {
      email: 'azureprivatedns-host.microsoft.com'
      expireTime: 2419200
      host: 'azureprivatedns.net'
      minimumTtl: 10
      refreshTime: 3600
      retryTime: 300
      serialNumber: 1
    }
  }
}

resource virtualNetworks_c964_vnet_name_virtualNetworks_c964_vnet_name_local_peering_link 'Microsoft.Network/virtualNetworks/virtualNetworkPeerings@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/${virtualNetworks_c964_vnet_name}-local-peering-link'
  properties: {
    peeringState: 'Disconnected'
    peeringSyncLevel: 'FullyInSync'
    remoteVirtualNetwork: {
      id: '${virtualNetworks_c964_vnet_name_resource.id}-centralus'
    }
    allowVirtualNetworkAccess: true
    allowForwardedTraffic: false
    allowGatewayTransit: false
    useRemoteGateways: false
    doNotVerifyRemoteGateways: false
    peerCompleteVnets: true
    remoteAddressSpace: {
      addressPrefixes: [
        '10.1.0.0/16'
      ]
    }
    remoteVirtualNetworkAddressSpace: {
      addressPrefixes: [
        '10.1.0.0/16'
      ]
    }
  }
}

resource namespaces_c964_relay_namespace_name_resource 'Microsoft.Relay/namespaces@2024-01-01' = {
  name: namespaces_c964_relay_namespace_name
  location: 'southcentralus'
  tags: {
    Environment: 'cloudshell'
  }
  sku: {
    name: 'Standard'
    tier: 'Standard'
  }
  properties: {
    publicNetworkAccess: 'Enabled'
    privateEndpointConnections: [
      {
        properties: {
          provisioningState: 'Succeeded'
          privateEndpoint: {
            id: privateEndpoints_cloudshellRelayEndpoint_name_resource.id
          }
          privateLinkServiceConnectionState: {
            status: 'Approved'
            description: 'Auto-Approved'
          }
        }
      }
    ]
  }
}

resource namespaces_c964_relay_namespace_name_RootManageSharedAccessKey 'Microsoft.Relay/namespaces/authorizationrules@2024-01-01' = {
  name: '${namespaces_c964_relay_namespace_name}/RootManageSharedAccessKey'
  location: 'southcentralus'
  properties: {
    rights: [
      'Listen'
      'Manage'
      'Send'
    ]
  }
  dependsOn: [
    namespaces_c964_relay_namespace_name_resource
  ]
}

resource namespaces_c964_relay_namespace_name_default 'Microsoft.Relay/namespaces/networkrulesets@2024-01-01' = {
  name: '${namespaces_c964_relay_namespace_name}/default'
  location: 'southcentralus'
  properties: {
    publicNetworkAccess: 'Enabled'
    defaultAction: 'Allow'
    ipRules: []
    trustedServiceAccessEnabled: false
  }
  dependsOn: [
    namespaces_c964_relay_namespace_name_resource
  ]
}

resource storageAccounts_c964cloudshellstore_name_resource 'Microsoft.Storage/storageAccounts@2025-01-01' = {
  name: storageAccounts_c964cloudshellstore_name
  location: 'southcentralus'
  tags: {
    'ms-resource-usage': 'azure-cloud-shell'
  }
  sku: {
    name: 'Standard_LRS'
    tier: 'Standard'
  }
  kind: 'StorageV2'
  properties: {
    dnsEndpointType: 'Standard'
    defaultToOAuthAuthentication: false
    publicNetworkAccess: 'Enabled'
    allowCrossTenantReplication: false
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    largeFileSharesState: 'Enabled'
    networkAcls: {
      bypass: 'AzureServices'
      virtualNetworkRules: [
        {
          id: virtualNetworks_c964_vnet_name_default.id
          action: 'Allow'
          state: 'Succeeded'
        }
      ]
      ipRules: []
      defaultAction: 'Deny'
    }
    supportsHttpsTrafficOnly: true
    encryption: {
      requireInfrastructureEncryption: false
      services: {
        file: {
          keyType: 'Account'
          enabled: true
        }
        blob: {
          keyType: 'Account'
          enabled: true
        }
      }
      keySource: 'Microsoft.Storage'
    }
    accessTier: 'Hot'
  }
}

resource storageAccounts_c964cloudshellstore_name_default 'Microsoft.Storage/storageAccounts/blobServices@2025-01-01' = {
  parent: storageAccounts_c964cloudshellstore_name_resource
  name: 'default'
  sku: {
    name: 'Standard_LRS'
    tier: 'Standard'
  }
  properties: {
    containerDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
    cors: {
      corsRules: []
    }
    deleteRetentionPolicy: {
      allowPermanentDelete: false
      enabled: true
      days: 7
    }
  }
}

resource storageAccounts_c964store_name_default 'Microsoft.Storage/storageAccounts/blobServices@2025-01-01' = {
  parent: storageAccounts_c964store_name_resource
  name: 'default'
  sku: {
    name: 'Standard_LRS'
    tier: 'Standard'
  }
  properties: {
    containerDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
    cors: {
      corsRules: []
    }
    deleteRetentionPolicy: {
      allowPermanentDelete: false
      enabled: true
      days: 7
    }
  }
}

resource Microsoft_Storage_storageAccounts_fileServices_storageAccounts_c964cloudshellstore_name_default 'Microsoft.Storage/storageAccounts/fileServices@2025-01-01' = {
  parent: storageAccounts_c964cloudshellstore_name_resource
  name: 'default'
  sku: {
    name: 'Standard_LRS'
    tier: 'Standard'
  }
  properties: {
    protocolSettings: {
      smb: {}
    }
    cors: {
      corsRules: []
    }
    shareDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}

resource Microsoft_Storage_storageAccounts_fileServices_storageAccounts_c964store_name_default 'Microsoft.Storage/storageAccounts/fileServices@2025-01-01' = {
  parent: storageAccounts_c964store_name_resource
  name: 'default'
  sku: {
    name: 'Standard_LRS'
    tier: 'Standard'
  }
  properties: {
    protocolSettings: {
      smb: {}
    }
    cors: {
      corsRules: []
    }
    shareDeleteRetentionPolicy: {
      enabled: true
      days: 7
    }
  }
}

resource storageAccounts_c964store_name_storageAccounts_c964store_name_24ab6acb_05b7_4847_82a4_2c74651fc50f 'Microsoft.Storage/storageAccounts/privateEndpointConnections@2025-01-01' = {
  parent: storageAccounts_c964store_name_resource
  name: '${storageAccounts_c964store_name}.24ab6acb-05b7-4847-82a4-2c74651fc50f'
  properties: {
    privateEndpoint: {}
    privateLinkServiceConnectionState: {
      status: 'Approved'
      description: 'Auto-Approved'
      actionRequired: 'None'
    }
  }
}

resource Microsoft_Storage_storageAccounts_queueServices_storageAccounts_c964cloudshellstore_name_default 'Microsoft.Storage/storageAccounts/queueServices@2025-01-01' = {
  parent: storageAccounts_c964cloudshellstore_name_resource
  name: 'default'
  properties: {
    cors: {
      corsRules: []
    }
  }
}

resource Microsoft_Storage_storageAccounts_queueServices_storageAccounts_c964store_name_default 'Microsoft.Storage/storageAccounts/queueServices@2025-01-01' = {
  parent: storageAccounts_c964store_name_resource
  name: 'default'
  properties: {
    cors: {
      corsRules: []
    }
  }
}

resource Microsoft_Storage_storageAccounts_tableServices_storageAccounts_c964cloudshellstore_name_default 'Microsoft.Storage/storageAccounts/tableServices@2025-01-01' = {
  parent: storageAccounts_c964cloudshellstore_name_resource
  name: 'default'
  properties: {
    cors: {
      corsRules: []
    }
  }
}

resource Microsoft_Storage_storageAccounts_tableServices_storageAccounts_c964store_name_default 'Microsoft.Storage/storageAccounts/tableServices@2025-01-01' = {
  parent: storageAccounts_c964store_name_resource
  name: 'default'
  properties: {
    cors: {
      corsRules: []
    }
  }
}

resource accounts_c964_openai_resource_name_c964aisearchbasic 'Microsoft.CognitiveServices/accounts/connections@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_resource
  name: 'c964aisearchbasic'
  properties: {
    authType: 'ApiKey'
    category: 'CognitiveSearch'
    target: 'https://c964-ai-search-basic.search.windows.net/'
    useWorkspaceManagedIdentity: false
    isSharedToAll: false
    sharedUserList: []
    peRequirement: 'NotRequired'
    peStatus: 'NotApplicable'
    metadata: {
      type: 'azure_ai_search'
      ApiType: 'Azure'
      ResourceId: searchServices_c964_ai_search_basic_name_resource.id
      ApiVersion: '2024-05-01-preview'
      DeploymentApiVersion: '2023-11-01'
    }
  }
}

resource privateDnsZones_privatelink_blob_core_windows_net_name_ajr4hc3n3qkwc 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZones_privatelink_blob_core_windows_net_name_resource
  name: 'ajr4hc3n3qkwc'
  location: 'global'
  properties: {
    registrationEnabled: false
    resolutionPolicy: 'Default'
    virtualNetwork: {
      id: virtualNetworks_c964_vnet_name_resource.id
    }
  }
}

resource privateDnsZones_privatelink_openai_azure_com_name_ajr4hc3n3qkwc 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZones_privatelink_openai_azure_com_name_resource
  name: 'ajr4hc3n3qkwc'
  location: 'global'
  properties: {
    registrationEnabled: false
    resolutionPolicy: 'Default'
    virtualNetwork: {
      id: virtualNetworks_c964_vnet_name_resource.id
    }
  }
}

resource privateDnsZones_privatelink_search_windows_net_name_ajr4hc3n3qkwc 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZones_privatelink_search_windows_net_name_resource
  name: 'ajr4hc3n3qkwc'
  location: 'global'
  properties: {
    registrationEnabled: false
    resolutionPolicy: 'Default'
    virtualNetwork: {
      id: virtualNetworks_c964_vnet_name_resource.id
    }
  }
}

resource privateDnsZones_privatelink_aiservices_azure_com_name_aszte24xrfhwk 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZones_privatelink_aiservices_azure_com_name_resource
  name: 'aszte24xrfhwk'
  location: 'global'
  properties: {
    registrationEnabled: false
    resolutionPolicy: 'Default'
    virtualNetwork: {
      id: virtualNetworks_c964_vnet_name_resource.id
    }
  }
}

resource Microsoft_Network_privateDnsZones_virtualNetworkLinks_privateDnsZones_privatelink_servicebus_windows_net_name_c964_relay_namespace 'Microsoft.Network/privateDnsZones/virtualNetworkLinks@2024-06-01' = {
  parent: privateDnsZones_privatelink_servicebus_windows_net_name_resource
  name: 'c964-relay-namespace'
  location: 'global'
  tags: {
    Environment: 'cloudshell'
  }
  properties: {
    registrationEnabled: false
    resolutionPolicy: 'Default'
    virtualNetwork: {
      id: virtualNetworks_c964_vnet_name_resource.id
    }
  }
}

resource privateEndpoints_ai_search_pep_name_resource 'Microsoft.Network/privateEndpoints@2024-07-01' = {
  name: privateEndpoints_ai_search_pep_name
  location: 'southcentralus'
  properties: {
    privateLinkServiceConnections: [
      {
        name: privateEndpoints_ai_search_pep_name
        id: '${privateEndpoints_ai_search_pep_name_resource.id}/privateLinkServiceConnections/${privateEndpoints_ai_search_pep_name}'
        properties: {
          privateLinkServiceId: searchServices_c964_ai_search_basic_name_resource.id
          groupIds: [
            'searchService'
          ]
          privateLinkServiceConnectionState: {
            status: 'Approved'
            description: 'Auto-approved'
            actionsRequired: 'None'
          }
        }
      }
    ]
    manualPrivateLinkServiceConnections: []
    customNetworkInterfaceName: '${privateEndpoints_ai_search_pep_name}-nic'
    subnet: {
      id: virtualNetworks_c964_vnet_name_privateendpoint.id
    }
    ipConfigurations: []
    customDnsConfigs: []
  }
}

resource privateEndpoints_c964storepep_name_resource 'Microsoft.Network/privateEndpoints@2024-07-01' = {
  name: privateEndpoints_c964storepep_name
  location: 'southcentralus'
  properties: {
    privateLinkServiceConnections: [
      {
        name: privateEndpoints_c964storepep_name
        id: '${privateEndpoints_c964storepep_name_resource.id}/privateLinkServiceConnections/${privateEndpoints_c964storepep_name}'
        properties: {
          privateLinkServiceId: storageAccounts_c964store_name_resource.id
          groupIds: [
            'blob'
          ]
          privateLinkServiceConnectionState: {
            status: 'Approved'
            description: 'Auto-Approved'
            actionsRequired: 'None'
          }
        }
      }
    ]
    manualPrivateLinkServiceConnections: []
    customNetworkInterfaceName: '${privateEndpoints_c964storepep_name}-nic'
    subnet: {
      id: virtualNetworks_c964_vnet_name_privateendpoint.id
    }
    ipConfigurations: []
    customDnsConfigs: []
  }
}

resource privateEndpoints_cloudshellRelayEndpoint_name_resource 'Microsoft.Network/privateEndpoints@2024-07-01' = {
  name: privateEndpoints_cloudshellRelayEndpoint_name
  location: 'southcentralus'
  tags: {
    Environment: 'cloudshell'
  }
  properties: {
    privateLinkServiceConnections: [
      {
        name: privateEndpoints_cloudshellRelayEndpoint_name
        id: '${privateEndpoints_cloudshellRelayEndpoint_name_resource.id}/privateLinkServiceConnections/${privateEndpoints_cloudshellRelayEndpoint_name}'
        properties: {
          privateLinkServiceId: namespaces_c964_relay_namespace_name_resource.id
          groupIds: [
            'namespace'
          ]
          privateLinkServiceConnectionState: {
            status: 'Approved'
            description: 'Auto-Approved'
            actionsRequired: 'None'
          }
        }
      }
    ]
    manualPrivateLinkServiceConnections: []
    subnet: {
      id: virtualNetworks_c964_vnet_name_relaysubnet.id
    }
    ipConfigurations: []
    customDnsConfigs: [
      {
        fqdn: 'c964-relay-namespace.servicebus.windows.net'
        ipAddresses: [
          '10.0.11.4'
        ]
      }
    ]
  }
}

resource privateEndpoints_ai_search_pep_name_default 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2024-07-01' = {
  name: '${privateEndpoints_ai_search_pep_name}/default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-search-windows-net'
        properties: {
          privateDnsZoneId: privateDnsZones_privatelink_search_windows_net_name_resource.id
        }
      }
    ]
  }
  dependsOn: [
    privateEndpoints_ai_search_pep_name_resource
  ]
}

resource privateEndpoints_c964storepep_name_default 'Microsoft.Network/privateEndpoints/privateDnsZoneGroups@2024-07-01' = {
  name: '${privateEndpoints_c964storepep_name}/default'
  properties: {
    privateDnsZoneConfigs: [
      {
        name: 'privatelink-blob-core-windows-net'
        properties: {
          privateDnsZoneId: privateDnsZones_privatelink_blob_core_windows_net_name_resource.id
        }
      }
    ]
  }
  dependsOn: [
    privateEndpoints_c964storepep_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_aifoundry 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/aifoundry'
  properties: {
    addressPrefix: '10.0.1.0/28'
    networkSecurityGroup: {
      id: networkSecurityGroups_aifoundry_nsg_name_resource.id
    }
    serviceEndpoints: [
      {
        service: 'Microsoft.Storage'
        locations: [
          'southcentralus'
          'northcentralus'
          'brazilsouth'
        ]
      }
      {
        service: 'Microsoft.CognitiveServices'
        locations: [
          '*'
        ]
      }
    ]
    delegations: []
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
    defaultOutboundAccess: false
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_cloudshellsubnet 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/cloudshellsubnet'
  properties: {
    addressPrefix: '10.0.10.0/26'
    networkSecurityGroup: {
      id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
    }
    serviceEndpoints: [
      {
        service: 'Microsoft.Storage'
        locations: [
          'southcentralus'
          'northcentralus'
          'brazilsouth'
        ]
      }
    ]
    delegations: [
      {
        name: 'CloudShellDelegation'
        id: '${virtualNetworks_c964_vnet_name_cloudshellsubnet.id}/delegations/CloudShellDelegation'
        properties: {
          serviceName: 'Microsoft.ContainerInstance/containerGroups'
        }
        type: 'Microsoft.Network/virtualNetworks/subnets/delegations'
      }
    ]
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_containerapps 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/containerapps'
  properties: {
    addressPrefix: '10.0.8.0/23'
    networkSecurityGroup: {
      id: networkSecurityGroups_c964_vnet_containerapps_nsg_southcentralus_name_resource.id
    }
    serviceEndpoints: []
    delegations: [
      {
        name: 'Microsoft.App.environments'
        id: '${virtualNetworks_c964_vnet_name_containerapps.id}/delegations/Microsoft.App.environments'
        properties: {
          serviceName: 'Microsoft.App/environments'
        }
        type: 'Microsoft.Network/virtualNetworks/subnets/delegations'
      }
    ]
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
    defaultOutboundAccess: false
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_default 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/default'
  properties: {
    addressPrefix: '10.0.0.0/24'
    networkSecurityGroup: {
      id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
    }
    serviceEndpoints: [
      {
        service: 'Microsoft.Storage'
        locations: [
          'southcentralus'
          'northcentralus'
          'brazilsouth'
        ]
      }
      {
        service: 'Microsoft.CognitiveServices'
        locations: [
          '*'
        ]
      }
    ]
    delegations: []
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
    defaultOutboundAccess: false
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_openai 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/openai'
  properties: {
    addressPrefix: '10.0.2.0/28'
    networkSecurityGroup: {
      id: networkSecurityGroups_c964_vnet_openai_nsg_southcentralus_name_resource.id
    }
    serviceEndpoints: [
      {
        service: 'Microsoft.Storage'
        locations: [
          'southcentralus'
          'northcentralus'
          'brazilsouth'
        ]
      }
      {
        service: 'Microsoft.CognitiveServices'
        locations: [
          '*'
        ]
      }
    ]
    delegations: []
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
    defaultOutboundAccess: false
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_privateendpoint 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/privateendpoint'
  properties: {
    addressPrefix: '10.0.6.0/27'
    networkSecurityGroup: {
      id: networkSecurityGroups_c964_vnet_privateendpoint_nsg_southcentralus_name_resource.id
    }
    serviceEndpoints: [
      {
        service: 'Microsoft.Storage'
        locations: [
          'southcentralus'
          'northcentralus'
          'brazilsouth'
        ]
      }
    ]
    delegations: []
    privateEndpointNetworkPolicies: 'Enabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
    defaultOutboundAccess: false
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_relaysubnet 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/relaysubnet'
  properties: {
    addressPrefix: '10.0.11.0/26'
    networkSecurityGroup: {
      id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
    }
    delegations: []
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_storagesubnet 'Microsoft.Network/virtualNetworks/subnets@2024-07-01' = {
  name: '${virtualNetworks_c964_vnet_name}/storagesubnet'
  properties: {
    addressPrefix: '10.0.12.0/26'
    networkSecurityGroup: {
      id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
    }
    serviceEndpoints: [
      {
        service: 'Microsoft.Storage'
        locations: [
          'southcentralus'
          'northcentralus'
          'brazilsouth'
        ]
      }
    ]
    delegations: []
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
  }
  dependsOn: [
    virtualNetworks_c964_vnet_name_resource
  ]
}

resource namespaces_c964_relay_namespace_name_78326441_9ff5_4a2d_802b_32245dfddea4 'Microsoft.Relay/namespaces/privateEndpointConnections@2024-01-01' = {
  name: '${namespaces_c964_relay_namespace_name}/78326441-9ff5-4a2d-802b-32245dfddea4'
  location: 'southcentralus'
  properties: {
    provisioningState: 'Succeeded'
    privateEndpoint: {
      id: privateEndpoints_cloudshellRelayEndpoint_name_resource.id
    }
    privateLinkServiceConnectionState: {
      status: 'Approved'
      description: 'Auto-Approved'
    }
  }
  dependsOn: [
    namespaces_c964_relay_namespace_name_resource
  ]
}

resource searchServices_c964_ai_search_basic_name_ai_search_pep_6d4adb19_3c17_43d8_b23a_5bc542a705f7 'Microsoft.Search/searchServices/privateEndpointConnections@2025-05-01' = {
  parent: searchServices_c964_ai_search_basic_name_resource
  name: 'ai-search-pep.6d4adb19-3c17-43d8-b23a-5bc542a705f7'
  properties: {
    privateEndpoint: {
      id: privateEndpoints_ai_search_pep_name_resource.id
    }
    privateLinkServiceConnectionState: {
      status: 'Approved'
      description: 'Auto-approved'
      actionsRequired: 'None'
    }
    provisioningState: 'Succeeded'
    groupId: 'searchService'
  }
}

resource storageAccounts_c964store_name_default_mldatasets 'Microsoft.Storage/storageAccounts/blobServices/containers@2025-01-01' = {
  parent: storageAccounts_c964store_name_default
  name: 'mldatasets'
  properties: {
    immutableStorageWithVersioning: {
      enabled: false
    }
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
    publicAccess: 'None'
  }
  dependsOn: [
    storageAccounts_c964store_name_resource
  ]
}

resource storageAccounts_c964store_name_default_rag_data 'Microsoft.Storage/storageAccounts/blobServices/containers@2025-01-01' = {
  parent: storageAccounts_c964store_name_default
  name: 'rag-data'
  properties: {
    immutableStorageWithVersioning: {
      enabled: false
    }
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
    publicAccess: 'None'
  }
  dependsOn: [
    storageAccounts_c964store_name_resource
  ]
}

resource storageAccounts_c964store_name_default_train_data 'Microsoft.Storage/storageAccounts/blobServices/containers@2025-01-01' = {
  parent: storageAccounts_c964store_name_default
  name: 'train-data'
  properties: {
    immutableStorageWithVersioning: {
      enabled: false
    }
    defaultEncryptionScope: '$account-encryption-key'
    denyEncryptionScopeOverride: false
    publicAccess: 'None'
  }
  dependsOn: [
    storageAccounts_c964store_name_resource
  ]
}

resource accounts_c964_openai_resource_name_c964_openai_c964aisearchbasic 'Microsoft.CognitiveServices/accounts/projects/connections@2025-06-01' = {
  parent: accounts_c964_openai_resource_name_c964_openai
  name: 'c964aisearchbasic'
  properties: {
    authType: 'ApiKey'
    category: 'CognitiveSearch'
    target: 'https://c964-ai-search-basic.search.windows.net/'
    useWorkspaceManagedIdentity: false
    isSharedToAll: false
    sharedUserList: []
    peRequirement: 'NotRequired'
    peStatus: 'NotApplicable'
    metadata: {
      type: 'azure_ai_search'
      ApiType: 'Azure'
      ResourceId: searchServices_c964_ai_search_basic_name_resource.id
      ApiVersion: '2024-05-01-preview'
      DeploymentApiVersion: '2023-11-01'
    }
  }
  dependsOn: [
    accounts_c964_openai_resource_name_resource
  ]
}

resource virtualNetworks_c964_vnet_name_resource 'Microsoft.Network/virtualNetworks@2024-07-01' = {
  name: virtualNetworks_c964_vnet_name
  location: 'southcentralus'
  properties: {
    addressSpace: {
      addressPrefixes: [
        '10.0.0.0/16'
      ]
    }
    encryption: {
      enabled: false
      enforcement: 'AllowUnencrypted'
    }
    privateEndpointVNetPolicies: 'Disabled'
    dhcpOptions: {
      dnsServers: []
    }
    subnets: [
      {
        name: 'default'
        id: virtualNetworks_c964_vnet_name_default.id
        properties: {
          addressPrefix: '10.0.0.0/24'
          networkSecurityGroup: {
            id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
          }
          serviceEndpoints: [
            {
              service: 'Microsoft.Storage'
              locations: [
                'southcentralus'
                'northcentralus'
                'brazilsouth'
              ]
            }
            {
              service: 'Microsoft.CognitiveServices'
              locations: [
                '*'
              ]
            }
          ]
          delegations: []
          privateEndpointNetworkPolicies: 'Disabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
          defaultOutboundAccess: false
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
      {
        name: 'aifoundry'
        id: virtualNetworks_c964_vnet_name_aifoundry.id
        properties: {
          addressPrefix: '10.0.1.0/28'
          networkSecurityGroup: {
            id: networkSecurityGroups_aifoundry_nsg_name_resource.id
          }
          serviceEndpoints: [
            {
              service: 'Microsoft.Storage'
              locations: [
                'southcentralus'
                'northcentralus'
                'brazilsouth'
              ]
            }
            {
              service: 'Microsoft.CognitiveServices'
              locations: [
                '*'
              ]
            }
          ]
          delegations: []
          privateEndpointNetworkPolicies: 'Disabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
          defaultOutboundAccess: false
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
      {
        name: 'openai'
        id: virtualNetworks_c964_vnet_name_openai.id
        properties: {
          addressPrefix: '10.0.2.0/28'
          networkSecurityGroup: {
            id: networkSecurityGroups_c964_vnet_openai_nsg_southcentralus_name_resource.id
          }
          serviceEndpoints: [
            {
              service: 'Microsoft.Storage'
              locations: [
                'southcentralus'
                'northcentralus'
                'brazilsouth'
              ]
            }
            {
              service: 'Microsoft.CognitiveServices'
              locations: [
                '*'
              ]
            }
          ]
          delegations: []
          privateEndpointNetworkPolicies: 'Disabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
          defaultOutboundAccess: false
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
      {
        name: 'privateendpoint'
        id: virtualNetworks_c964_vnet_name_privateendpoint.id
        properties: {
          addressPrefix: '10.0.6.0/27'
          networkSecurityGroup: {
            id: networkSecurityGroups_c964_vnet_privateendpoint_nsg_southcentralus_name_resource.id
          }
          serviceEndpoints: [
            {
              service: 'Microsoft.Storage'
              locations: [
                'southcentralus'
                'northcentralus'
                'brazilsouth'
              ]
            }
          ]
          delegations: []
          privateEndpointNetworkPolicies: 'Enabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
          defaultOutboundAccess: false
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
      {
        name: 'containerapps'
        id: virtualNetworks_c964_vnet_name_containerapps.id
        properties: {
          addressPrefix: '10.0.8.0/23'
          networkSecurityGroup: {
            id: networkSecurityGroups_c964_vnet_containerapps_nsg_southcentralus_name_resource.id
          }
          serviceEndpoints: []
          delegations: [
            {
              name: 'Microsoft.App.environments'
              id: '${virtualNetworks_c964_vnet_name_containerapps.id}/delegations/Microsoft.App.environments'
              properties: {
                serviceName: 'Microsoft.App/environments'
              }
              type: 'Microsoft.Network/virtualNetworks/subnets/delegations'
            }
          ]
          privateEndpointNetworkPolicies: 'Disabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
          defaultOutboundAccess: false
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
      {
        name: 'cloudshellsubnet'
        id: virtualNetworks_c964_vnet_name_cloudshellsubnet.id
        properties: {
          addressPrefix: '10.0.10.0/26'
          networkSecurityGroup: {
            id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
          }
          serviceEndpoints: [
            {
              service: 'Microsoft.Storage'
              locations: [
                'southcentralus'
                'northcentralus'
                'brazilsouth'
              ]
            }
          ]
          delegations: [
            {
              name: 'CloudShellDelegation'
              id: '${virtualNetworks_c964_vnet_name_cloudshellsubnet.id}/delegations/CloudShellDelegation'
              properties: {
                serviceName: 'Microsoft.ContainerInstance/containerGroups'
              }
              type: 'Microsoft.Network/virtualNetworks/subnets/delegations'
            }
          ]
          privateEndpointNetworkPolicies: 'Disabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
      {
        name: 'relaysubnet'
        id: virtualNetworks_c964_vnet_name_relaysubnet.id
        properties: {
          addressPrefix: '10.0.11.0/26'
          networkSecurityGroup: {
            id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
          }
          delegations: []
          privateEndpointNetworkPolicies: 'Disabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
      {
        name: 'storagesubnet'
        id: virtualNetworks_c964_vnet_name_storagesubnet.id
        properties: {
          addressPrefix: '10.0.12.0/26'
          networkSecurityGroup: {
            id: networkSecurityGroups_c964_vnet_default_nsg_southcentralus_name_resource.id
          }
          serviceEndpoints: [
            {
              service: 'Microsoft.Storage'
              locations: [
                'southcentralus'
                'northcentralus'
                'brazilsouth'
              ]
            }
          ]
          delegations: []
          privateEndpointNetworkPolicies: 'Disabled'
          privateLinkServiceNetworkPolicies: 'Enabled'
        }
        type: 'Microsoft.Network/virtualNetworks/subnets'
      }
    ]
    virtualNetworkPeerings: [
      {
        name: '${virtualNetworks_c964_vnet_name}-local-peering-link'
        id: virtualNetworks_c964_vnet_name_virtualNetworks_c964_vnet_name_local_peering_link.id
        properties: {
          peeringState: 'Disconnected'
          peeringSyncLevel: 'FullyInSync'
          remoteVirtualNetwork: {
            id: '${virtualNetworks_c964_vnet_name_resource.id}-centralus'
          }
          allowVirtualNetworkAccess: true
          allowForwardedTraffic: false
          allowGatewayTransit: false
          useRemoteGateways: false
          doNotVerifyRemoteGateways: false
          peerCompleteVnets: true
          remoteAddressSpace: {
            addressPrefixes: [
              '10.1.0.0/16'
            ]
          }
          remoteVirtualNetworkAddressSpace: {
            addressPrefixes: [
              '10.1.0.0/16'
            ]
          }
        }
        type: 'Microsoft.Network/virtualNetworks/virtualNetworkPeerings'
      }
    ]
    enableDdosProtection: false
  }
}

resource storageAccounts_c964store_name_resource 'Microsoft.Storage/storageAccounts@2025-01-01' = {
  name: storageAccounts_c964store_name
  location: 'southcentralus'
  tags: {
    'ms-resource-usage': 'azure-cloud-shell'
  }
  sku: {
    name: 'Standard_LRS'
    tier: 'Standard'
  }
  kind: 'StorageV2'
  properties: {
    dnsEndpointType: 'Standard'
    defaultToOAuthAuthentication: true
    publicNetworkAccess: 'Disabled'
    allowCrossTenantReplication: false
    azureFilesIdentityBasedAuthentication: {
      smbOAuthSettings: {
        isSmbOAuthEnabled: false
      }
      directoryServiceOptions: 'None'
    }
    minimumTlsVersion: 'TLS1_2'
    allowBlobPublicAccess: false
    allowSharedKeyAccess: false
    largeFileSharesState: 'Enabled'
    networkAcls: {
      resourceAccessRules: [
        {
          tenantId: '16b3c013-d300-468d-ac64-7eda0820b6d3'
          resourceId: searchServices_c964_ai_search_basic_name_resource.id
        }
      ]
      bypass: 'AzureServices'
      virtualNetworkRules: [
        {
          id: virtualNetworks_c964_vnet_name_default.id
          action: 'Allow'
          state: 'Succeeded'
        }
        {
          id: virtualNetworks_c964_vnet_name_aifoundry.id
          action: 'Allow'
          state: 'Succeeded'
        }
        {
          id: virtualNetworks_c964_vnet_name_openai.id
          action: 'Allow'
          state: 'Succeeded'
        }
        {
          id: virtualNetworks_c964_vnet_name_privateendpoint.id
          action: 'Allow'
          state: 'Succeeded'
        }
      ]
      ipRules: [
        {
          value: '72.66.71.33'
          action: 'Allow'
        }
        {
          value: '52.177.6.190'
          action: 'Allow'
        }
        {
          value: '20.120.96.152'
          action: 'Allow'
        }
        {
          value: '52.167.112.163'
          action: 'Allow'
        }
      ]
      defaultAction: 'Deny'
    }
    supportsHttpsTrafficOnly: true
    encryption: {
      requireInfrastructureEncryption: false
      services: {
        file: {
          keyType: 'Account'
          enabled: true
        }
        blob: {
          keyType: 'Account'
          enabled: true
        }
      }
      keySource: 'Microsoft.Storage'
    }
    accessTier: 'Hot'
  }
}
